openapi: "3.0.0"
info:
  description: Obfuss API Documentation
  title: Obfuss API
  version: 1.0.0
  x-go-package: "github.com/oapi-codegen/runtime"

host: localhost:6996
basePath: /api
servers:
  - url: http://localhost
paths:
  /jadwal-kuliah:
    get:
      consumes:
        - application/json
      description: Get jadwal Kuliah
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: size
          schema:
            type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/components/schemas/models.GetAllJadwalKuliahResponse"
      security:
        - BearerAuth: []
      summary: Get Jadwal Kuliah
      tags:
        - Jadwal Kuliah
components:
  schemas:
    BaseResponse:
      type: object
      x-go-type-skip-optional-pointer: true
      required:
        - responseCode
        - responseMessage
      properties:
        responseCode:
          type: string
          x-go-type-skip-optional-pointer: true
        responseMessage:
          type: string
          x-go-type-skip-optional-pointer: true
    models.GetAllJadwalKuliahResponse:
      properties:
        id_kelas:
          type: integer
        inisial_kelas:
          type: string
        jumlah_mk:
          type: integer
        kode_kurikulum:
          type: integer
        nama_kelas:
          type: string
        nama_konsentrasi:
          type: string
        nama_prodi:
          type: string
        semester:
          type: string
        tahun:
          type: string
      type: object
