// Package boilerplate provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package boilerplate

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// EntitiesAngketDosen defines model for entities.AngketDosen.
type EntitiesAngketDosen struct {
	AddDate          *string `json:"add_date,omitempty"`
	AddUser          *int    `json:"add_user,omitempty"`
	File             *string `json:"file,omitempty"`
	FileGambar       *string `json:"file_gambar,omitempty"`
	Id               *int    `json:"id,omitempty"`
	IdDosen          *int    `json:"id_dosen,omitempty"`
	IdPertemuan      *int    `json:"id_pertemuan,omitempty"`
	JamKuliah        *string `json:"jam_kuliah,omitempty"`
	JumlahDaring     *int    `json:"jumlah_daring,omitempty"`
	JumlahHadir      *int    `json:"jumlah_hadir,omitempty"`
	JumlahLuring     *int    `json:"jumlah_luring,omitempty"`
	JumlahTidakHadir *int    `json:"jumlah_tidak_hadir,omitempty"`
	Keterangan       *string `json:"keterangan,omitempty"`
	ModifiedDate     *string `json:"modified_date,omitempty"`
	ModifiedUser     *int    `json:"modified_user,omitempty"`
	PertemuanKe      *int    `json:"pertemuan_ke,omitempty"`
	RingkasanMateri  *string `json:"ringkasan_materi,omitempty"`
	Status           *string `json:"status,omitempty"`
}

// EntitiesKelas defines model for entities.Kelas.
type EntitiesKelas struct {
	AddDate        *string              `json:"add_date,omitempty"`
	AddUser        *int                 `json:"add_user,omitempty"`
	Id             *int                 `json:"id,omitempty"`
	Idkonsentrasi  *int                 `json:"idkonsentrasi,omitempty"`
	Idkurikulum    *int                 `json:"idkurikulum,omitempty"`
	Idsemester     *int                 `json:"idsemester,omitempty"`
	InisialKelas   *string              `json:"inisialKelas,omitempty"`
	Keterangan     *string              `json:"keterangan,omitempty"`
	Konsentrasi    *EntitiesKonsentrasi `json:"konsentrasi,omitempty"`
	Kurikulum      *EntitiesKurikulum   `json:"kurikulum,omitempty"`
	ModifiedDate   *string              `json:"modified_date,omitempty"`
	ModifiedUser   *int                 `json:"modified_user,omitempty"`
	NamaKelas      *string              `json:"namaKelas,omitempty"`
	Semester       *EntitiesSemester    `json:"semester,omitempty"`
	SemesterKuliah *string              `json:"semesterKuliah,omitempty"`
}

// EntitiesKonsentrasi defines model for entities.Konsentrasi.
type EntitiesKonsentrasi struct {
	AddDate         *string `json:"add_date,omitempty"`
	AddUser         *int    `json:"add_user,omitempty"`
	Gelar           *string `json:"gelar,omitempty"`
	Id              *int    `json:"id,omitempty"`
	InisialGelar    *string `json:"inisial_gelar,omitempty"`
	Jurusan         *string `json:"jurusan,omitempty"`
	Keterangan      *string `json:"keterangan,omitempty"`
	KodeProdi       *int    `json:"kode_prodi,omitempty"`
	ModifiedDate    *string `json:"modified_date,omitempty"`
	ModifiedUser    *int    `json:"modified_user,omitempty"`
	NamaKonsentrasi *string `json:"nama_konsentrasi,omitempty"`
	NamaProdi       *string `json:"nama_prodi,omitempty"`
	PejabatTte      *int    `json:"pejabat_tte,omitempty"`
	TranslateGelar  *string `json:"translate_gelar,omitempty"`
}

// EntitiesKurikulum defines model for entities.Kurikulum.
type EntitiesKurikulum struct {
	ActiveStatus   *string `json:"active_status,omitempty"`
	AddDate        *string `json:"add_date,omitempty"`
	AddUser        *int    `json:"add_user,omitempty"`
	Id             *int    `json:"id,omitempty"`
	KodeKurikulum  *string `json:"kode_kurikulum,omitempty"`
	ModifiedDate   *string `json:"modified_date,omitempty"`
	ModifiedUser   *int    `json:"modified_user,omitempty"`
	MulaiKurikulum *string `json:"mulai_kurikulum,omitempty"`
	SksPilihan     *int    `json:"sks_pilihan,omitempty"`
	SksWajib       *int    `json:"sks_wajib,omitempty"`
}

// EntitiesSemester defines model for entities.Semester.
type EntitiesSemester struct {
	ActiveStatus    *string              `json:"active_status,omitempty"`
	AddDate         *string              `json:"add_date,omitempty"`
	AddUser         *int                 `json:"add_user,omitempty"`
	Id              *int                 `json:"id,omitempty"`
	IdTahun         *int                 `json:"id_tahun,omitempty"`
	ModifiedDate    *string              `json:"modified_date,omitempty"`
	ModifiedUser    *int                 `json:"modified_user,omitempty"`
	Semester        *string              `json:"semester,omitempty"`
	TahunAjaran     *EntitiesTahunAjaran `json:"tahun_ajaran,omitempty"`
	TanggalBerakhir *string              `json:"tanggal_berakhir,omitempty"`
	TanggalMulai    *string              `json:"tanggal_mulai,omitempty"`
}

// EntitiesTahunAjaran defines model for entities.TahunAjaran.
type EntitiesTahunAjaran struct {
	ActiveStatus  *string `json:"active_status,omitempty"`
	AddDate       *string `json:"add_date,omitempty"`
	AddUser       *int    `json:"add_user,omitempty"`
	Id            *int    `json:"id,omitempty"`
	ModifiedDate  *string `json:"modified_date,omitempty"`
	ModifiedUser  *int    `json:"modified_user,omitempty"`
	MulaiBerjalan *string `json:"mulai_berjalan,omitempty"`
	Tahun         *string `json:"tahun,omitempty"`
}

// HandlersTokenResponse defines model for handlers.TokenResponse.
type HandlersTokenResponse struct {
	TokenDosen *string `json:"token_dosen,omitempty"`
	TokenMhs   *string `json:"token_mhs,omitempty"`
}

// ModelsBaseResponseAny defines model for models.BaseResponse-any.
type ModelsBaseResponseAny struct {
	Data    *map[string]interface{}   `json:"data,omitempty"`
	Errors  *[]map[string]interface{} `json:"errors,omitempty"`
	Message *string                   `json:"message,omitempty"`
	Meta    *ModelsPaginationMeta     `json:"meta,omitempty"`
}

// ModelsBaseResponseArrayEntitiesKelas defines model for models.BaseResponse-array_entities_Kelas.
type ModelsBaseResponseArrayEntitiesKelas struct {
	Data    *[]EntitiesKelas          `json:"data,omitempty"`
	Errors  *[]map[string]interface{} `json:"errors,omitempty"`
	Message *string                   `json:"message,omitempty"`
	Meta    *ModelsPaginationMeta     `json:"meta,omitempty"`
}

// ModelsBaseResponseArrayModelsGetAllDosen defines model for models.BaseResponse-array_models_GetAllDosen.
type ModelsBaseResponseArrayModelsGetAllDosen struct {
	Data    *[]ModelsGetAllDosen      `json:"data,omitempty"`
	Errors  *[]map[string]interface{} `json:"errors,omitempty"`
	Message *string                   `json:"message,omitempty"`
	Meta    *ModelsPaginationMeta     `json:"meta,omitempty"`
}

// ModelsBaseResponseArrayModelsGetAllJadwalKuliahResponse defines model for models.BaseResponse-array_models_GetAllJadwalKuliahResponse.
type ModelsBaseResponseArrayModelsGetAllJadwalKuliahResponse struct {
	Data    *[]ModelsGetAllJadwalKuliahResponse `json:"data,omitempty"`
	Errors  *[]map[string]interface{}           `json:"errors,omitempty"`
	Message *string                             `json:"message,omitempty"`
	Meta    *ModelsPaginationMeta               `json:"meta,omitempty"`
}

// ModelsBaseResponseArrayModelsGetAllJamKuliah defines model for models.BaseResponse-array_models_GetAllJamKuliah.
type ModelsBaseResponseArrayModelsGetAllJamKuliah struct {
	Data    *[]ModelsGetAllJamKuliah  `json:"data,omitempty"`
	Errors  *[]map[string]interface{} `json:"errors,omitempty"`
	Message *string                   `json:"message,omitempty"`
	Meta    *ModelsPaginationMeta     `json:"meta,omitempty"`
}

// ModelsBaseResponseArrayModelsGetAllPerubahanJadwal defines model for models.BaseResponse-array_models_GetAllPerubahanJadwal.
type ModelsBaseResponseArrayModelsGetAllPerubahanJadwal struct {
	Data    *[]ModelsGetAllPerubahanJadwal `json:"data,omitempty"`
	Errors  *[]map[string]interface{}      `json:"errors,omitempty"`
	Message *string                        `json:"message,omitempty"`
	Meta    *ModelsPaginationMeta          `json:"meta,omitempty"`
}

// ModelsBaseResponseArrayModelsMataKuliah defines model for models.BaseResponse-array_models_MataKuliah.
type ModelsBaseResponseArrayModelsMataKuliah struct {
	Data    *[]ModelsMataKuliah       `json:"data,omitempty"`
	Errors  *[]map[string]interface{} `json:"errors,omitempty"`
	Message *string                   `json:"message,omitempty"`
	Meta    *ModelsPaginationMeta     `json:"meta,omitempty"`
}

// ModelsBaseResponseEntitiesAngketDosen defines model for models.BaseResponse-entities_AngketDosen.
type ModelsBaseResponseEntitiesAngketDosen struct {
	Data    *EntitiesAngketDosen      `json:"data,omitempty"`
	Errors  *[]map[string]interface{} `json:"errors,omitempty"`
	Message *string                   `json:"message,omitempty"`
	Meta    *ModelsPaginationMeta     `json:"meta,omitempty"`
}

// ModelsBaseResponseHandlersTokenResponse defines model for models.BaseResponse-handlers_TokenResponse.
type ModelsBaseResponseHandlersTokenResponse struct {
	Data    *HandlersTokenResponse    `json:"data,omitempty"`
	Errors  *[]map[string]interface{} `json:"errors,omitempty"`
	Message *string                   `json:"message,omitempty"`
	Meta    *ModelsPaginationMeta     `json:"meta,omitempty"`
}

// ModelsBaseResponseModelsGetAllAbsenResponse defines model for models.BaseResponse-models_GetAllAbsenResponse.
type ModelsBaseResponseModelsGetAllAbsenResponse struct {
	Data    *ModelsGetAllAbsenResponse `json:"data,omitempty"`
	Errors  *[]map[string]interface{}  `json:"errors,omitempty"`
	Message *string                    `json:"message,omitempty"`
	Meta    *ModelsPaginationMeta      `json:"meta,omitempty"`
}

// ModelsGetAllAbsenResponse defines model for models.GetAllAbsenResponse.
type ModelsGetAllAbsenResponse struct {
	DayNumber       *int    `json:"day_number,omitempty"`
	Hari            *string `json:"hari,omitempty"`
	Id              *int    `json:"id,omitempty"`
	IdKelas         *int    `json:"id_kelas,omitempty"`
	IdMk            *int    `json:"id_mk,omitempty"`
	IdPertemuan     *int    `json:"id_pertemuan,omitempty"`
	IdSemester      *int    `json:"id_semester,omitempty"`
	InisialKelas    *string `json:"inisial_kelas,omitempty"`
	JamMulai        *string `json:"jam_mulai,omitempty"`
	JamSelesai      *string `json:"jam_selesai,omitempty"`
	JumlahHadir     *int    `json:"jumlah_hadir,omitempty"`
	JumlahPertemuan *int    `json:"jumlah_pertemuan,omitempty"`
	KodeKurikulum   *string `json:"kode_kurikulum,omitempty"`
	NamaDosen       *string `json:"nama_dosen,omitempty"`
	NamaKelas       *string `json:"nama_kelas,omitempty"`
	NamaKonsentrasi *string `json:"nama_konsentrasi,omitempty"`
	NamaLengkap     *string `json:"nama_lengkap,omitempty"`
	NamaMk          *string `json:"nama_mk,omitempty"`
	NamaProdi       *string `json:"nama_prodi,omitempty"`
	Semester        *string `json:"semester,omitempty"`
	Tahun           *string `json:"tahun,omitempty"`
}

// ModelsGetAllDosen defines model for models.GetAllDosen.
type ModelsGetAllDosen struct {
	Id          *int    `json:"id,omitempty"`
	Kelamin     *string `json:"kelamin,omitempty"`
	Keterangan  *string `json:"keterangan,omitempty"`
	NamaLengkap *string `json:"nama_lengkap,omitempty"`
	Nidn        *string `json:"nidn,omitempty"`
	Nik         *string `json:"nik,omitempty"`
	Nip         *string `json:"nip,omitempty"`
	Nupn        *string `json:"nupn,omitempty"`
	Status      *string `json:"status,omitempty"`
	Uname       *string `json:"uname,omitempty"`
}

// ModelsGetAllJadwalKuliahResponse defines model for models.GetAllJadwalKuliahResponse.
type ModelsGetAllJadwalKuliahResponse struct {
	IdKelas         *int    `json:"id_kelas,omitempty"`
	InisialKelas    *string `json:"inisial_kelas,omitempty"`
	JumlahMk        *int    `json:"jumlah_mk,omitempty"`
	KodeKurikulum   *int    `json:"kode_kurikulum,omitempty"`
	NamaKelas       *string `json:"nama_kelas,omitempty"`
	NamaKonsentrasi *string `json:"nama_konsentrasi,omitempty"`
	NamaProdi       *string `json:"nama_prodi,omitempty"`
	Semester        *string `json:"semester,omitempty"`
	Tahun           *string `json:"tahun,omitempty"`
}

// ModelsGetAllJamKuliah defines model for models.GetAllJamKuliah.
type ModelsGetAllJamKuliah struct {
	Id         *int    `json:"id,omitempty"`
	JamMulai   *string `json:"jam_mulai,omitempty"`
	JamSelesai *string `json:"jam_selesai,omitempty"`
	Keterangan *string `json:"keterangan,omitempty"`
	NoUrut     *int    `json:"no_urut,omitempty"`
}

// ModelsGetAllPerubahanJadwal defines model for models.GetAllPerubahanJadwal.
type ModelsGetAllPerubahanJadwal struct {
	AlasanPerubahan    *string `json:"alasan_perubahan,omitempty"`
	HariJadwal         *string `json:"hari_jadwal,omitempty"`
	HariOld            *string `json:"hari_old,omitempty"`
	Id                 *int    `json:"id,omitempty"`
	InisialKelas       *string `json:"inisial_kelas,omitempty"`
	JamKuliah          *string `json:"jam_kuliah,omitempty"`
	JamKuliahOld       *string `json:"jam_kuliah_old,omitempty"`
	Keterangan         *string `json:"keterangan,omitempty"`
	KodeKurikulum      *string `json:"kode_kurikulum,omitempty"`
	MulaiJam           *int    `json:"mulai_jam,omitempty"`
	MulaiJamOld        *int    `json:"mulai_jam_old,omitempty"`
	NamaDosen          *string `json:"nama_dosen,omitempty"`
	NamaKelas          *string `json:"nama_kelas,omitempty"`
	NamaKonsentrasi    *string `json:"nama_konsentrasi,omitempty"`
	NamaMk             *string `json:"nama_mk,omitempty"`
	NamaProdi          *string `json:"nama_prodi,omitempty"`
	SampaiJam          *int    `json:"sampai_jam,omitempty"`
	SampaiJamOld       *int    `json:"sampai_jam_old,omitempty"`
	Semester           *string `json:"semester,omitempty"`
	StatusUsulan       *string `json:"status_usulan,omitempty"`
	Tahun              *string `json:"tahun,omitempty"`
	TanggalOld         *string `json:"tanggal_old,omitempty"`
	TanggalPertemuan   *string `json:"tanggal_pertemuan,omitempty"`
	TanggalUsulanGanti *string `json:"tanggal_usulan_ganti,omitempty"`
}

// ModelsGetMahasiswaRaw defines model for models.GetMahasiswaRaw.
type ModelsGetMahasiswaRaw struct {
	IdKelas     *int `json:"id_kelas,omitempty"`
	IdPertemuan *int `json:"id_pertemuan,omitempty"`
}

// ModelsJadwalKuliahCreateRequest defines model for models.JadwalKuliahCreateRequest.
type ModelsJadwalKuliahCreateRequest struct {
	Hari         string `json:"hari"`
	IdDosen      int    `json:"id_dosen"`
	IdJamMulai   int    `json:"id_jam_mulai"`
	IdJamSelesai int    `json:"id_jam_selesai"`
	IdMk         int    `json:"id_mk"`
}

// ModelsJadwalKuliahRequest defines model for models.JadwalKuliahRequest.
type ModelsJadwalKuliahRequest struct {
	IdKelas      int                               `json:"id_kelas"`
	JadwalKuliah []ModelsJadwalKuliahCreateRequest `json:"jadwal_kuliah"`
}

// ModelsLaporanPerkuliahanDTO defines model for models.LaporanPerkuliahanDTO.
type ModelsLaporanPerkuliahanDTO struct {
	IdDosen     int   `json:"idDosen"`
	IdKelas     int   `json:"idKelas"`
	IdMk        int   `json:"idMk"`
	IdPertemuan int   `json:"idPertemuan"`
	IsPreview   *bool `json:"isPreview,omitempty"`
}

// ModelsMataKuliah defines model for models.MataKuliah.
type ModelsMataKuliah struct {
	Id             *int    `json:"id,omitempty"`
	IsAgama        *int    `json:"is_agama,omitempty"`
	IsTaPkl        *string `json:"is_ta_pkl,omitempty"`
	JenisMk        *string `json:"jenis_mk,omitempty"`
	Keterangan     *string `json:"keterangan,omitempty"`
	KodeMk         *string `json:"kode_mk,omitempty"`
	NamaMk         *string `json:"nama_mk,omitempty"`
	SemesterKuliah *int    `json:"semester_kuliah,omitempty"`
	Sks            *int    `json:"sks,omitempty"`
	SksLapangan    *int    `json:"sks_lapangan,omitempty"`
	SksPraktek     *int    `json:"sks_praktek,omitempty"`
	SksSimulasi    *int    `json:"sks_simulasi,omitempty"`
	Status         *string `json:"status,omitempty"`
}

// ModelsPaginationMeta defines model for models.PaginationMeta.
type ModelsPaginationMeta struct {
	Page      *int `json:"page,omitempty"`
	Size      *int `json:"size,omitempty"`
	Total     *int `json:"total,omitempty"`
	TotalPage *int `json:"totalPage,omitempty"`
}

// ModelsSaveAbsenTransRequest defines model for models.SaveAbsenTransRequest.
type ModelsSaveAbsenTransRequest struct {
	Absen       []ModelsSaveTransAbsen `json:"absen"`
	IdJadwal    int                    `json:"id_jadwal"`
	IdKelas     int                    `json:"id_kelas"`
	IdPertemuan int                    `json:"id_pertemuan"`
}

// ModelsSaveTransAbsen defines model for models.SaveTransAbsen.
type ModelsSaveTransAbsen struct {
	IdMahasiswa int `json:"id_mahasiswa"`

	// IsHadir yes or no
	IsHadir *string `json:"is_hadir,omitempty"`

	// Keterangan daring or luring
	Keterangan *string `json:"keterangan,omitempty"`
}

// ModelsSaveTransJadwalKuliahDosen defines model for models.SaveTransJadwalKuliahDosen.
type ModelsSaveTransJadwalKuliahDosen struct {
	Hari         *string `json:"hari,omitempty"`
	Id           *int    `json:"id,omitempty"`
	IdDosen      *int    `json:"id_dosen,omitempty"`
	IdJamMulai   *int    `json:"id_jam_mulai,omitempty"`
	IdJamSelesai *int    `json:"id_jam_selesai,omitempty"`
	IdKelas      *int    `json:"id_kelas,omitempty"`
	IdMk         *int    `json:"id_mk,omitempty"`
	IdSemester   *int    `json:"id_semester,omitempty"`
}

// ModelsUpdateJadwalPertemuanRequest defines model for models.UpdateJadwalPertemuanRequest.
type ModelsUpdateJadwalPertemuanRequest struct {
	AlasanPerubahan    *string `json:"alasan_perubahan,omitempty"`
	IdJadwalKuliah     *int    `json:"id_jadwal_kuliah,omitempty"`
	StatusUsulan       *string `json:"status_usulan,omitempty"`
	TanggalUsulanGanti *string `json:"tanggal_usulan_ganti,omitempty"`
	UsulanMulaiJam     *int    `json:"usulan_mulai_jam,omitempty"`
	UsulanSampaiJam    *int    `json:"usulan_sampai_jam,omitempty"`
}

// GetJadwalKuliahParams defines parameters for GetJadwalKuliah.
type GetJadwalKuliahParams struct {
	Page *int `form:"page,omitempty" json:"page,omitempty"`
	Size *int `form:"size,omitempty" json:"size,omitempty"`
}

// GetJadwalKuliahDosenParams defines parameters for GetJadwalKuliahDosen.
type GetJadwalKuliahDosenParams struct {
	// Page Page
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Limit
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostJadwalKuliahDosenMahasiswaParams defines parameters for PostJadwalKuliahDosenMahasiswa.
type PostJadwalKuliahDosenMahasiswaParams struct {
	// Page Page
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Limit
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetLaporanPerkuliahanParams defines parameters for GetLaporanPerkuliahan.
type GetLaporanPerkuliahanParams struct {
	// Page Page
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Limit
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostLaporanPerkuliahanSaveTransFormdataBody defines parameters for PostLaporanPerkuliahanSaveTrans.
type PostLaporanPerkuliahanSaveTransFormdataBody struct {
	FileName *string `form:"fileName,omitempty" json:"fileName,omitempty"`

	// Foto file
	Foto        *openapi_types.File `form:"foto,omitempty" json:"foto,omitempty"`
	IdDosen     int32               `form:"id_dosen" json:"id_dosen"`
	IdPertemuan int32               `form:"id_pertemuan" json:"id_pertemuan"`
	JamKuliah   string              `form:"jam_kuliah" json:"jam_kuliah"`
	Keterangan  string              `form:"keterangan" json:"keterangan"`
	Materi      string              `form:"materi" json:"materi"`
	PertemuanKe int32               `form:"pertemuan_ke" json:"pertemuan_ke"`
}

// GetMahasiswaAbsenParams defines parameters for GetMahasiswaAbsen.
type GetMahasiswaAbsenParams struct {
	Page *int `form:"page,omitempty" json:"page,omitempty"`
	Size *int `form:"size,omitempty" json:"size,omitempty"`

	// SmtId Semester ID
	SmtId int `form:"smtId" json:"smtId"`

	// KelasId Kelas ID
	KelasId int `form:"kelasId" json:"kelasId"`
}

// GetPerubahanJadwalParams defines parameters for GetPerubahanJadwal.
type GetPerubahanJadwalParams struct {
	Page *int `form:"page,omitempty" json:"page,omitempty"`
	Size *int `form:"size,omitempty" json:"size,omitempty"`
}

// PostJadwalKuliahDosenMahasiswaJSONRequestBody defines body for PostJadwalKuliahDosenMahasiswa for application/json ContentType.
type PostJadwalKuliahDosenMahasiswaJSONRequestBody = ModelsGetMahasiswaRaw

// PostJadwalKuliahDosenSaveTransJSONRequestBody defines body for PostJadwalKuliahDosenSaveTrans for application/json ContentType.
type PostJadwalKuliahDosenSaveTransJSONRequestBody = ModelsSaveTransJadwalKuliahDosen

// PostJadwalKuliahSaveTransJSONRequestBody defines body for PostJadwalKuliahSaveTrans for application/json ContentType.
type PostJadwalKuliahSaveTransJSONRequestBody = ModelsJadwalKuliahRequest

// PostLaporanPerkuliahanSaveTransFormdataRequestBody defines body for PostLaporanPerkuliahanSaveTrans for application/x-www-form-urlencoded ContentType.
type PostLaporanPerkuliahanSaveTransFormdataRequestBody PostLaporanPerkuliahanSaveTransFormdataBody

// PostLaporanPerkuliahanToPdfJSONRequestBody defines body for PostLaporanPerkuliahanToPdf for application/json ContentType.
type PostLaporanPerkuliahanToPdfJSONRequestBody = ModelsLaporanPerkuliahanDTO

// PostMahasiswaAbsenSaveTransJSONRequestBody defines body for PostMahasiswaAbsenSaveTrans for application/json ContentType.
type PostMahasiswaAbsenSaveTransJSONRequestBody = ModelsSaveAbsenTransRequest

// PatchPerubahanJadwalIdJadwalPertemuanJSONRequestBody defines body for PatchPerubahanJadwalIdJadwalPertemuan for application/json ContentType.
type PatchPerubahanJadwalIdJadwalPertemuanJSONRequestBody = ModelsUpdateJadwalPertemuanRequest
