// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/absen/mahasiswa": {
            "get": {
                "description": "Get Absen Mahasiswa",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Absen"
                ],
                "summary": "Get Absen Mahasiswa",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User type",
                        "name": "userType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Semester ID",
                        "name": "smtId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Kelas ID",
                        "name": "kelasId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-models_GetAllAbsenResponse"
                        }
                    }
                }
            }
        },
        "/todo": {
            "get": {
                "description": "Get Todos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todo"
                ],
                "summary": "Get Todos",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-array_entities_Todo"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Todo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todo"
                ],
                "summary": "Create Todo",
                "parameters": [
                    {
                        "description": "Todo",
                        "name": "todo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TodoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-entities_Todo"
                        }
                    }
                }
            }
        },
        "/todo/{id}": {
            "get": {
                "description": "Get Todo By ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todo"
                ],
                "summary": "Get Todo By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-entities_Todo"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Todo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todo"
                ],
                "summary": "Update Todo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Todo",
                        "name": "todo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TodoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-entities_Todo"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Todo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todo"
                ],
                "summary": "Delete Todo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-entities_Todo"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.Todo": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "Action is the todo action",
                    "type": "string"
                },
                "createdAt": {
                    "description": "Automatically managed by GORM for creation time",
                    "type": "string"
                },
                "id": {
                    "description": "Standard field for the primary key",
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "Automatically managed by GORM for update time",
                    "type": "string"
                }
            }
        },
        "models.BaseResponse-array_entities_Todo": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Todo"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.BaseResponse-entities_Todo": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/entities.Todo"
                },
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.BaseResponse-models_GetAllAbsenResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.GetAllAbsenResponse"
                },
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.GetAllAbsenResponse": {
            "type": "object",
            "properties": {
                "day_number": {
                    "type": "integer"
                },
                "hari": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_kelas": {
                    "type": "integer"
                },
                "id_mk": {
                    "type": "integer"
                },
                "id_pertemuan": {
                    "type": "integer"
                },
                "id_semester": {
                    "type": "integer"
                },
                "inisial_kelas": {
                    "type": "string"
                },
                "jam_mulai": {
                    "type": "string"
                },
                "jam_selesai": {
                    "type": "string"
                },
                "jumlah_hadir": {
                    "type": "integer"
                },
                "jumlah_pertemuan": {
                    "type": "integer"
                },
                "kode_kurikulum": {
                    "type": "string"
                },
                "nama_dosen": {
                    "type": "string"
                },
                "nama_kelas": {
                    "type": "string"
                },
                "nama_konsentrasi": {
                    "type": "string"
                },
                "nama_lengkap": {
                    "type": "string"
                },
                "nama_mk": {
                    "type": "string"
                },
                "nama_prodi": {
                    "type": "string"
                },
                "semester": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                }
            }
        },
        "models.PaginationMeta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPage": {
                    "type": "integer"
                }
            }
        },
        "models.TodoRequest": {
            "type": "object",
            "required": [
                "action"
            ],
            "properties": {
                "action": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1",
	Host:             "localhost:6996",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Obfuss API",
	Description:      "Obfuss API Documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
