// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/jadwal-kuliah": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get jadwal Kuliah",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jadwal Kuliah"
                ],
                "summary": "Get Jadwal Kuliah",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-array_entities_JadwalKuliah"
                        }
                    }
                }
            }
        },
        "/jadwal-kuliah-dosen/save-trans": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Save Trans Jadwal Kuliah",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jadwal Kuliah"
                ],
                "summary": "Save Trans Jadwal Kuliah",
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/jadwal-kuliah/": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "delete Trans Jadwal Kuliah",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jadwal Kuliah"
                ],
                "summary": "delete Trans Jadwal Kuliah",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Jadwal Kuliah ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/jadwal-kuliah/save-trans": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Save Trans Jadwal Kuliah",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jadwal Kuliah"
                ],
                "summary": "Save Trans Jadwal Kuliah",
                "parameters": [
                    {
                        "description": "Save Trans request",
                        "name": "jadwalKuliah",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.JadwalKuliahRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/mahasiswa": {
            "get": {
                "description": "Get Absen Mahasiswa",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Absen"
                ],
                "summary": "Get Absen Mahasiswa",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User type",
                        "name": "userType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Semester ID",
                        "name": "smtId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Kelas ID",
                        "name": "kelasId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-models_GetAllAbsenResponse"
                        }
                    }
                }
            }
        },
        "/mahasiswa/absen/save-trans": {
            "post": {
                "description": "Save Absen",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Absen"
                ],
                "summary": "Save Absen Trans",
                "parameters": [
                    {
                        "description": "Absen request",
                        "name": "absen",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SaveAbsenTransRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/perubahan-jadwal": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Perubahan Jadwal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Perubahan Jadwal"
                ],
                "summary": "Get Perubahan Jadwal",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-array_models_GetAllPerubahanJadwal"
                        }
                    }
                }
            }
        },
        "/todo": {
            "get": {
                "description": "Get Todos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todo"
                ],
                "summary": "Get Todos",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-array_entities_Todo"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Todo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todo"
                ],
                "summary": "Create Todo",
                "parameters": [
                    {
                        "description": "Todo",
                        "name": "todo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TodoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-entities_Todo"
                        }
                    }
                }
            }
        },
        "/todo/{id}": {
            "get": {
                "description": "Get Todo By ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todo"
                ],
                "summary": "Get Todo By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-entities_Todo"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Todo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todo"
                ],
                "summary": "Update Todo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Todo",
                        "name": "todo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TodoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-entities_Todo"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Todo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todo"
                ],
                "summary": "Delete Todo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-entities_Todo"
                        }
                    }
                }
            }
        },
        "/token": {
            "get": {
                "description": "Get Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Token"
                ],
                "summary": "Get Token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-handlers_TokenResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.JadwalKuliah": {
            "type": "object",
            "properties": {
                "add_date": {
                    "type": "string"
                },
                "add_user": {
                    "type": "integer"
                },
                "hari": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_dosen": {
                    "type": "integer"
                },
                "id_jam_mulai": {
                    "type": "integer"
                },
                "id_jam_selesai": {
                    "type": "integer"
                },
                "id_kelas": {
                    "type": "integer"
                },
                "id_mk": {
                    "type": "integer"
                },
                "id_semester": {
                    "type": "integer"
                },
                "kelas": {
                    "$ref": "#/definitions/entities.Kelas"
                },
                "modified_date": {
                    "type": "string"
                },
                "modified_user": {
                    "type": "integer"
                },
                "semester": {
                    "$ref": "#/definitions/entities.Semester"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "entities.Kelas": {
            "type": "object",
            "properties": {
                "add_date": {
                    "type": "string"
                },
                "add_user": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "idkonsentrasi": {
                    "type": "integer"
                },
                "idkurikulum": {
                    "type": "integer"
                },
                "idsemester": {
                    "type": "integer"
                },
                "inisialKelas": {
                    "type": "string"
                },
                "keterangan": {
                    "type": "string"
                },
                "konsentrasi": {
                    "$ref": "#/definitions/entities.Konsentrasi"
                },
                "kurikulum": {
                    "$ref": "#/definitions/entities.Kurikulum"
                },
                "modified_date": {
                    "type": "string"
                },
                "modified_user": {
                    "type": "integer"
                },
                "namaKelas": {
                    "type": "string"
                },
                "semester": {
                    "$ref": "#/definitions/entities.Semester"
                },
                "semesterKuliah": {
                    "type": "string"
                }
            }
        },
        "entities.Konsentrasi": {
            "type": "object",
            "properties": {
                "add_date": {
                    "type": "string"
                },
                "add_user": {
                    "type": "integer"
                },
                "gelar": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "inisial_gelar": {
                    "type": "string"
                },
                "jurusan": {
                    "type": "string"
                },
                "keterangan": {
                    "type": "string"
                },
                "kode_prodi": {
                    "type": "integer"
                },
                "modified_date": {
                    "type": "string"
                },
                "modified_user": {
                    "type": "integer"
                },
                "nama_konsentrasi": {
                    "type": "string"
                },
                "nama_prodi": {
                    "type": "string"
                },
                "pejabat_tte": {
                    "type": "integer"
                },
                "translate_gelar": {
                    "type": "string"
                }
            }
        },
        "entities.Kurikulum": {
            "type": "object",
            "properties": {
                "active_status": {
                    "type": "string"
                },
                "add_date": {
                    "type": "string"
                },
                "add_user": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "kode_kurikulum": {
                    "type": "string"
                },
                "modified_date": {
                    "type": "string"
                },
                "modified_user": {
                    "type": "integer"
                },
                "mulai_kurikulum": {
                    "type": "string"
                },
                "sks_pilihan": {
                    "type": "integer"
                },
                "sks_wajib": {
                    "type": "integer"
                }
            }
        },
        "entities.Semester": {
            "type": "object",
            "properties": {
                "active_status": {
                    "type": "string"
                },
                "add_date": {
                    "type": "string"
                },
                "add_user": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "id_tahun": {
                    "type": "integer"
                },
                "modified_date": {
                    "type": "string"
                },
                "modified_user": {
                    "type": "integer"
                },
                "semester": {
                    "type": "string"
                },
                "tahun_ajaran": {
                    "$ref": "#/definitions/entities.TahunAjaran"
                },
                "tanggal_berakhir": {
                    "type": "string"
                },
                "tanggal_mulai": {
                    "type": "string"
                }
            }
        },
        "entities.TahunAjaran": {
            "type": "object",
            "properties": {
                "active_status": {
                    "type": "string"
                },
                "add_date": {
                    "type": "string"
                },
                "add_user": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "modified_date": {
                    "type": "string"
                },
                "modified_user": {
                    "type": "integer"
                },
                "mulai_berjalan": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                }
            }
        },
        "entities.Todo": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "Action is the todo action",
                    "type": "string"
                },
                "createdAt": {
                    "description": "Automatically managed by GORM for creation time",
                    "type": "string"
                },
                "id": {
                    "description": "Standard field for the primary key",
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "Automatically managed by GORM for update time",
                    "type": "string"
                }
            }
        },
        "handlers.TokenResponse": {
            "type": "object",
            "properties": {
                "token_dosen": {
                    "type": "string"
                },
                "token_mhs": {
                    "type": "string"
                }
            }
        },
        "models.BaseResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.BaseResponse-array_entities_JadwalKuliah": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.JadwalKuliah"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.BaseResponse-array_entities_Todo": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Todo"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.BaseResponse-array_models_GetAllPerubahanJadwal": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GetAllPerubahanJadwal"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.BaseResponse-entities_Todo": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/entities.Todo"
                },
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.BaseResponse-handlers_TokenResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handlers.TokenResponse"
                },
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.BaseResponse-models_GetAllAbsenResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.GetAllAbsenResponse"
                },
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.GetAllAbsenResponse": {
            "type": "object",
            "properties": {
                "day_number": {
                    "type": "integer"
                },
                "hari": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_kelas": {
                    "type": "integer"
                },
                "id_mk": {
                    "type": "integer"
                },
                "id_pertemuan": {
                    "type": "integer"
                },
                "id_semester": {
                    "type": "integer"
                },
                "inisial_kelas": {
                    "type": "string"
                },
                "jam_mulai": {
                    "type": "string"
                },
                "jam_selesai": {
                    "type": "string"
                },
                "jumlah_hadir": {
                    "type": "integer"
                },
                "jumlah_pertemuan": {
                    "type": "integer"
                },
                "kode_kurikulum": {
                    "type": "string"
                },
                "nama_dosen": {
                    "type": "string"
                },
                "nama_kelas": {
                    "type": "string"
                },
                "nama_konsentrasi": {
                    "type": "string"
                },
                "nama_lengkap": {
                    "type": "string"
                },
                "nama_mk": {
                    "type": "string"
                },
                "nama_prodi": {
                    "type": "string"
                },
                "semester": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                }
            }
        },
        "models.GetAllPerubahanJadwal": {
            "type": "object",
            "properties": {
                "alasan_perubahan": {
                    "type": "string"
                },
                "hari_jadwal": {
                    "type": "string"
                },
                "hari_old": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "inisial_kelas": {
                    "type": "string"
                },
                "jam_kuliah": {
                    "type": "string"
                },
                "jam_kuliah_old": {
                    "type": "string"
                },
                "keterangan": {
                    "type": "string"
                },
                "kode_kurikulum": {
                    "type": "string"
                },
                "mulai_jam": {
                    "type": "integer"
                },
                "mulai_jam_old": {
                    "type": "integer"
                },
                "nama_dosen": {
                    "type": "string"
                },
                "nama_kelas": {
                    "type": "string"
                },
                "nama_konsentrasi": {
                    "type": "string"
                },
                "nama_mk": {
                    "type": "string"
                },
                "nama_prodi": {
                    "type": "string"
                },
                "sampai_jam": {
                    "type": "integer"
                },
                "sampai_jam_old": {
                    "type": "integer"
                },
                "semester": {
                    "type": "string"
                },
                "status_usulan": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                },
                "tanggal_old": {
                    "type": "string"
                },
                "tanggal_pertemuan": {
                    "type": "string"
                },
                "tanggal_usulan_ganti": {
                    "type": "string"
                }
            }
        },
        "models.JadwalKuliahCreateRequest": {
            "type": "object",
            "required": [
                "hari",
                "id_dosen",
                "id_jam_mulai",
                "id_jam_selesai",
                "id_mk"
            ],
            "properties": {
                "hari": {
                    "type": "string"
                },
                "id_dosen": {
                    "type": "integer"
                },
                "id_jam_mulai": {
                    "type": "integer"
                },
                "id_jam_selesai": {
                    "type": "integer"
                },
                "id_mk": {
                    "type": "integer"
                }
            }
        },
        "models.JadwalKuliahRequest": {
            "type": "object",
            "required": [
                "id_kelas",
                "jadwal_kuliah"
            ],
            "properties": {
                "id_kelas": {
                    "type": "integer"
                },
                "jadwal_kuliah": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.JadwalKuliahCreateRequest"
                    }
                }
            }
        },
        "models.PaginationMeta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPage": {
                    "type": "integer"
                }
            }
        },
        "models.SaveAbsenTransRequest": {
            "type": "object",
            "required": [
                "absen",
                "id_jadwal",
                "id_kelas",
                "id_pertemuan"
            ],
            "properties": {
                "absen": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SaveTransAbsen"
                    }
                },
                "id_jadwal": {
                    "type": "integer",
                    "example": 1
                },
                "id_kelas": {
                    "type": "integer",
                    "example": 1
                },
                "id_pertemuan": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.SaveTransAbsen": {
            "type": "object",
            "required": [
                "id_mahasiswa"
            ],
            "properties": {
                "id_mahasiswa": {
                    "type": "integer",
                    "example": 1
                },
                "is_hadir": {
                    "description": "yes or no",
                    "type": "string",
                    "example": "yes"
                },
                "keterangan": {
                    "description": "daring or luring",
                    "type": "string",
                    "example": "daring"
                }
            }
        },
        "models.TodoRequest": {
            "type": "object",
            "required": [
                "action"
            ],
            "properties": {
                "action": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1",
	Host:             "localhost:6996",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Obfuss API",
	Description:      "Obfuss API Documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
