// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/jadwal-kuliah": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get jadwal Kuliah",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jadwal Kuliah"
                ],
                "summary": "Get Jadwal Kuliah",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-array_models_GetAllJadwalKuliahResponse"
                        }
                    }
                }
            }
        },
        "/jadwal-kuliah-dosen/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get All Jadwal Kuliah Dosen",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jadwal Kuliah"
                ],
                "summary": "Get All Jadwal Kuliah Dosen",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/jadwal-kuliah-dosen/kelas": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get All Kelas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jadwal Kuliah"
                ],
                "summary": "Get All Kelas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-array_entities_Kelas"
                        }
                    }
                }
            }
        },
        "/jadwal-kuliah-dosen/mahasiswa": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get All Mahasiswa",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jadwal Kuliah"
                ],
                "summary": "Get All Mahasiswa",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GetMahasiswaRaw"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/jadwal-kuliah-dosen/save-trans": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Save Trans Jadwal Kuliah",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jadwal Kuliah"
                ],
                "summary": "Save Trans Jadwal Kuliah",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SaveTransJadwalKuliahDosen"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/jadwal-kuliah-dosen/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "delete Trans Jadwal Kuliah",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jadwal Kuliah"
                ],
                "summary": "delete Trans Jadwal Kuliah",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Jadwal Kuliah ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/jadwal-kuliah/": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "delete Trans Jadwal Kuliah",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jadwal Kuliah"
                ],
                "summary": "delete Trans Jadwal Kuliah",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Jadwal Kuliah ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/jadwal-kuliah/save-trans": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Save Trans Jadwal Kuliah",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jadwal Kuliah"
                ],
                "summary": "Save Trans Jadwal Kuliah",
                "parameters": [
                    {
                        "description": "Save Trans request",
                        "name": "jadwalKuliah",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.JadwalKuliahRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/laporan-perkuliahan/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get All Laporan Perkuliahan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Laporan Perkuliahan"
                ],
                "summary": "Get All Laporan Perkuliahan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/laporan-perkuliahan/save-trans": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "SaveTrans",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Laporan Perkuliahan"
                ],
                "summary": "SaveTrans",
                "parameters": [
                    {
                        "type": "string",
                        "name": "fileName",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "id_dosen",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "id_pertemuan",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "jam_kuliah",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "keterangan",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "materi",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "pertemuan_ke",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "file",
                        "name": "foto",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/laporan-perkuliahan/to-pdf": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "To PDF",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "Laporan Perkuliahan"
                ],
                "summary": "To PDF",
                "parameters": [
                    {
                        "description": "Save Trans request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LaporanPerkuliahanDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/laporan-perkuliahan/{id-pertemuan}/pertemuan": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get All Laporan Perkuliahan By Pertemuan",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Laporan Perkuliahan"
                ],
                "summary": "Get All Laporan Perkuliahan By Pertemuan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pertemuan ID",
                        "name": "id-pertemuan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-entities_AngketDosen"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Angket Dosen",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Laporan Perkuliahan"
                ],
                "summary": "Delete Angket Dosen",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pertemuan ID",
                        "name": "id-pertemuan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/mahasiswa/absen": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Absen Mahasiswa",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Absen"
                ],
                "summary": "Get Absen Mahasiswa",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Semester ID",
                        "name": "smtId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Kelas ID",
                        "name": "kelasId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-models_GetAllAbsenResponse"
                        }
                    }
                }
            }
        },
        "/mahasiswa/absen/save-trans": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Save Absen",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Absen"
                ],
                "summary": "Save Absen Trans",
                "parameters": [
                    {
                        "description": "Absen request",
                        "name": "absen",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SaveAbsenTransRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/mahasiswa/absen/{idPertemuan}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete Absen",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Absen"
                ],
                "summary": "Delete Absen",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pertemuan ID",
                        "name": "idPertemuan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/perubahan-jadwal": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Perubahan Jadwal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Perubahan Jadwal"
                ],
                "summary": "Get Perubahan Jadwal",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-array_models_GetAllPerubahanJadwal"
                        }
                    }
                }
            }
        },
        "/perubahan-jadwal/{idJadwalPertemuan}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update Perubahan Jadwal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Perubahan Jadwal"
                ],
                "summary": "Update Perubahan Jadwal",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Jadwal Pertemuan",
                        "name": "idJadwalPertemuan",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Jadwal Pertemuan Request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateJadwalPertemuanRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/token": {
            "get": {
                "description": "Get Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Token"
                ],
                "summary": "Get Token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BaseResponse-handlers_TokenResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.AngketDosen": {
            "type": "object",
            "properties": {
                "add_date": {
                    "type": "string"
                },
                "add_user": {
                    "type": "integer"
                },
                "file": {
                    "type": "string"
                },
                "file_gambar": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_dosen": {
                    "type": "integer"
                },
                "id_pertemuan": {
                    "type": "integer"
                },
                "jam_kuliah": {
                    "type": "string"
                },
                "jumlah_daring": {
                    "type": "integer"
                },
                "jumlah_hadir": {
                    "type": "integer"
                },
                "jumlah_luring": {
                    "type": "integer"
                },
                "jumlah_tidak_hadir": {
                    "type": "integer"
                },
                "keterangan": {
                    "type": "string"
                },
                "modified_date": {
                    "type": "string"
                },
                "modified_user": {
                    "type": "integer"
                },
                "pertemuan_ke": {
                    "type": "integer"
                },
                "ringkasan_materi": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "entities.Kelas": {
            "type": "object",
            "properties": {
                "add_date": {
                    "type": "string"
                },
                "add_user": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "idkonsentrasi": {
                    "type": "integer"
                },
                "idkurikulum": {
                    "type": "integer"
                },
                "idsemester": {
                    "type": "integer"
                },
                "inisialKelas": {
                    "type": "string"
                },
                "keterangan": {
                    "type": "string"
                },
                "konsentrasi": {
                    "$ref": "#/definitions/entities.Konsentrasi"
                },
                "kurikulum": {
                    "$ref": "#/definitions/entities.Kurikulum"
                },
                "modified_date": {
                    "type": "string"
                },
                "modified_user": {
                    "type": "integer"
                },
                "namaKelas": {
                    "type": "string"
                },
                "semester": {
                    "$ref": "#/definitions/entities.Semester"
                },
                "semesterKuliah": {
                    "type": "string"
                }
            }
        },
        "entities.Konsentrasi": {
            "type": "object",
            "properties": {
                "add_date": {
                    "type": "string"
                },
                "add_user": {
                    "type": "integer"
                },
                "gelar": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "inisial_gelar": {
                    "type": "string"
                },
                "jurusan": {
                    "type": "string"
                },
                "keterangan": {
                    "type": "string"
                },
                "kode_prodi": {
                    "type": "integer"
                },
                "modified_date": {
                    "type": "string"
                },
                "modified_user": {
                    "type": "integer"
                },
                "nama_konsentrasi": {
                    "type": "string"
                },
                "nama_prodi": {
                    "type": "string"
                },
                "pejabat_tte": {
                    "type": "integer"
                },
                "translate_gelar": {
                    "type": "string"
                }
            }
        },
        "entities.Kurikulum": {
            "type": "object",
            "properties": {
                "active_status": {
                    "type": "string"
                },
                "add_date": {
                    "type": "string"
                },
                "add_user": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "kode_kurikulum": {
                    "type": "string"
                },
                "modified_date": {
                    "type": "string"
                },
                "modified_user": {
                    "type": "integer"
                },
                "mulai_kurikulum": {
                    "type": "string"
                },
                "sks_pilihan": {
                    "type": "integer"
                },
                "sks_wajib": {
                    "type": "integer"
                }
            }
        },
        "entities.Semester": {
            "type": "object",
            "properties": {
                "active_status": {
                    "type": "string"
                },
                "add_date": {
                    "type": "string"
                },
                "add_user": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "id_tahun": {
                    "type": "integer"
                },
                "modified_date": {
                    "type": "string"
                },
                "modified_user": {
                    "type": "integer"
                },
                "semester": {
                    "type": "string"
                },
                "tahun_ajaran": {
                    "$ref": "#/definitions/entities.TahunAjaran"
                },
                "tanggal_berakhir": {
                    "type": "string"
                },
                "tanggal_mulai": {
                    "type": "string"
                }
            }
        },
        "entities.TahunAjaran": {
            "type": "object",
            "properties": {
                "active_status": {
                    "type": "string"
                },
                "add_date": {
                    "type": "string"
                },
                "add_user": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "modified_date": {
                    "type": "string"
                },
                "modified_user": {
                    "type": "integer"
                },
                "mulai_berjalan": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                }
            }
        },
        "handlers.TokenResponse": {
            "type": "object",
            "properties": {
                "token_dosen": {
                    "type": "string"
                },
                "token_mhs": {
                    "type": "string"
                }
            }
        },
        "models.BaseResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.BaseResponse-array_entities_Kelas": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Kelas"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.BaseResponse-array_models_GetAllJadwalKuliahResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GetAllJadwalKuliahResponse"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.BaseResponse-array_models_GetAllPerubahanJadwal": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GetAllPerubahanJadwal"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.BaseResponse-entities_AngketDosen": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/entities.AngketDosen"
                },
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.BaseResponse-handlers_TokenResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handlers.TokenResponse"
                },
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.BaseResponse-models_GetAllAbsenResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.GetAllAbsenResponse"
                },
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "meta": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.GetAllAbsenResponse": {
            "type": "object",
            "properties": {
                "day_number": {
                    "type": "integer"
                },
                "hari": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_kelas": {
                    "type": "integer"
                },
                "id_mk": {
                    "type": "integer"
                },
                "id_pertemuan": {
                    "type": "integer"
                },
                "id_semester": {
                    "type": "integer"
                },
                "inisial_kelas": {
                    "type": "string"
                },
                "jam_mulai": {
                    "type": "string"
                },
                "jam_selesai": {
                    "type": "string"
                },
                "jumlah_hadir": {
                    "type": "integer"
                },
                "jumlah_pertemuan": {
                    "type": "integer"
                },
                "kode_kurikulum": {
                    "type": "string"
                },
                "nama_dosen": {
                    "type": "string"
                },
                "nama_kelas": {
                    "type": "string"
                },
                "nama_konsentrasi": {
                    "type": "string"
                },
                "nama_lengkap": {
                    "type": "string"
                },
                "nama_mk": {
                    "type": "string"
                },
                "nama_prodi": {
                    "type": "string"
                },
                "semester": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                }
            }
        },
        "models.GetAllJadwalKuliahResponse": {
            "type": "object",
            "properties": {
                "id_kelas": {
                    "type": "integer"
                },
                "inisial_kelas": {
                    "type": "string"
                },
                "jumlah_mk": {
                    "type": "integer"
                },
                "kode_kurikulum": {
                    "type": "integer"
                },
                "nama_kelas": {
                    "type": "string"
                },
                "nama_konsentrasi": {
                    "type": "string"
                },
                "nama_prodi": {
                    "type": "string"
                },
                "semester": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                }
            }
        },
        "models.GetAllPerubahanJadwal": {
            "type": "object",
            "properties": {
                "alasan_perubahan": {
                    "type": "string"
                },
                "hari_jadwal": {
                    "type": "string"
                },
                "hari_old": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "inisial_kelas": {
                    "type": "string"
                },
                "jam_kuliah": {
                    "type": "string"
                },
                "jam_kuliah_old": {
                    "type": "string"
                },
                "keterangan": {
                    "type": "string"
                },
                "kode_kurikulum": {
                    "type": "string"
                },
                "mulai_jam": {
                    "type": "integer"
                },
                "mulai_jam_old": {
                    "type": "integer"
                },
                "nama_dosen": {
                    "type": "string"
                },
                "nama_kelas": {
                    "type": "string"
                },
                "nama_konsentrasi": {
                    "type": "string"
                },
                "nama_mk": {
                    "type": "string"
                },
                "nama_prodi": {
                    "type": "string"
                },
                "sampai_jam": {
                    "type": "integer"
                },
                "sampai_jam_old": {
                    "type": "integer"
                },
                "semester": {
                    "type": "string"
                },
                "status_usulan": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                },
                "tanggal_old": {
                    "type": "string"
                },
                "tanggal_pertemuan": {
                    "type": "string"
                },
                "tanggal_usulan_ganti": {
                    "type": "string"
                }
            }
        },
        "models.GetMahasiswaRaw": {
            "type": "object",
            "properties": {
                "id_kelas": {
                    "type": "integer"
                },
                "id_pertemuan": {
                    "type": "integer"
                }
            }
        },
        "models.JadwalKuliahCreateRequest": {
            "type": "object",
            "required": [
                "hari",
                "id_dosen",
                "id_jam_mulai",
                "id_jam_selesai",
                "id_mk"
            ],
            "properties": {
                "hari": {
                    "type": "string"
                },
                "id_dosen": {
                    "type": "integer"
                },
                "id_jam_mulai": {
                    "type": "integer"
                },
                "id_jam_selesai": {
                    "type": "integer"
                },
                "id_mk": {
                    "type": "integer"
                }
            }
        },
        "models.JadwalKuliahRequest": {
            "type": "object",
            "required": [
                "id_kelas",
                "jadwal_kuliah"
            ],
            "properties": {
                "id_kelas": {
                    "type": "integer"
                },
                "jadwal_kuliah": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.JadwalKuliahCreateRequest"
                    }
                }
            }
        },
        "models.LaporanPerkuliahanDTO": {
            "type": "object",
            "required": [
                "idDosen",
                "idKelas",
                "idMk",
                "idPertemuan"
            ],
            "properties": {
                "idDosen": {
                    "type": "integer"
                },
                "idKelas": {
                    "type": "integer"
                },
                "idMk": {
                    "type": "integer"
                },
                "idPertemuan": {
                    "type": "integer"
                },
                "isPreview": {
                    "type": "boolean"
                }
            }
        },
        "models.PaginationMeta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPage": {
                    "type": "integer"
                }
            }
        },
        "models.SaveAbsenTransRequest": {
            "type": "object",
            "required": [
                "absen",
                "id_jadwal",
                "id_kelas",
                "id_pertemuan"
            ],
            "properties": {
                "absen": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SaveTransAbsen"
                    }
                },
                "id_jadwal": {
                    "type": "integer",
                    "example": 1
                },
                "id_kelas": {
                    "type": "integer",
                    "example": 1
                },
                "id_pertemuan": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.SaveTransAbsen": {
            "type": "object",
            "required": [
                "id_mahasiswa"
            ],
            "properties": {
                "id_mahasiswa": {
                    "type": "integer",
                    "example": 1
                },
                "is_hadir": {
                    "description": "yes or no",
                    "type": "string",
                    "example": "yes"
                },
                "keterangan": {
                    "description": "daring or luring",
                    "type": "string",
                    "example": "daring"
                }
            }
        },
        "models.SaveTransJadwalKuliahDosen": {
            "type": "object",
            "properties": {
                "hari": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_dosen": {
                    "type": "integer"
                },
                "id_jam_mulai": {
                    "type": "integer"
                },
                "id_jam_selesai": {
                    "type": "integer"
                },
                "id_kelas": {
                    "type": "integer"
                },
                "id_mk": {
                    "type": "integer"
                },
                "id_semester": {
                    "type": "integer"
                }
            }
        },
        "models.UpdateJadwalPertemuanRequest": {
            "type": "object",
            "properties": {
                "alasan_perubahan": {
                    "type": "string"
                },
                "id_jadwal": {
                    "type": "integer",
                    "example": 1
                },
                "status_usulan": {
                    "type": "string",
                    "example": "disetujui"
                },
                "tanggal_usulan_ganti": {
                    "type": "string",
                    "example": "2006-01-02 15:04:05"
                },
                "usulan_mulai_jam": {
                    "type": "integer",
                    "example": 1
                },
                "usulan_sampai_jam": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1",
	Host:             "localhost:6996",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Obfuss API",
	Description:      "Obfuss API Documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
